name: Automated Readme Generator

on:
  pull_request:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.9' # install the python version needed

      # - name: install python packages
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r .github/requirements.txt

      - name: execute py script
        run: python .github/run.py
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "updated readme" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}