name: Automated Readme Generator

on:
  pull_request:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-20.04 #ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10' # install the python version needed
      # - name: install python packages
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r .github/requirements.txt
      - name: execute py script
        run: python .github/run.py
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add -A
          git commit -m "updated readme" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}